version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  airflow-webserver:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "true"
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      KAFKA_TOPIC_STRIPE_INVOICE: stripe.invoice_events
      KAFKA_TOPIC_JOB_FETCH: job_postings.fetch_jobs
      KAFKA_TOPIC_JOB_DLQ: job_postings.dlq
      BQ_STG_JOB_POSTINGS_TABLE: stg_job_postings
      S3_PREFIX_JOB_POSTINGS: curated/job_postings
      BQ_CHECKPOINT_TABLE: etl_loaded_s3_keys_job_postings
      BQ_DATASET: lead_platform
      POLL_WINDOW_SECONDS: 86400
      CURSOR_FILE: /opt/airflow/project/.cursor_invoice_paid.json

      # ✅ AWS (S3)
      AWS_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET: load-insight-raw-wonjun

      # ✅ GCP (BigQuery) - 서비스계정 키 파일 경로
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/secrets/gcp-sa.json
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./secrets:/opt/airflow/secrets
      - ..:/opt/airflow/project
    ports:
      - "8080:8080"
    command: webserver

  airflow-scheduler:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"

      AWS_REGION: ap-northeast-2
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET: load-insight-raw-wonjun
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      KAFKA_TOPIC_STRIPE_INVOICE: stripe.invoice_events
      KAFKA_TOPIC_JOB_FETCH: job_postings.fetch_jobs
      KAFKA_TOPIC_JOB_DLQ: job_postings.dlq
      BQ_STG_JOB_POSTINGS_TABLE: stg_job_postings
      S3_PREFIX_JOB_POSTINGS: curated/job_postings
      BQ_CHECKPOINT_TABLE: etl_loaded_s3_keys_job_postings
      BQ_DATASET: lead_platform
      POLL_WINDOW_SECONDS: 86400
      CURSOR_FILE: /opt/airflow/project/.cursor_invoice_paid.json

      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/secrets/gcp-sa.json
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./secrets:/opt/airflow/secrets
      - ..:/opt/airflow/project
    command: scheduler
  
  airflow-init:
    build: .
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
      KAFKA_TOPIC_STRIPE_INVOICE: stripe.invoice_events
      KAFKA_TOPIC_JOB_FETCH: job_postings.fetch_jobs
      KAFKA_TOPIC_JOB_DLQ: job_postings.dlq
      BQ_STG_JOB_POSTINGS_TABLE: stg_job_postings
      S3_PREFIX_JOB_POSTINGS: curated/job_postings
      BQ_CHECKPOINT_TABLE: etl_loaded_s3_keys_job_postings
      GOOGLE_APPLICATION_CREDENTIALS: /opt/airflow/secrets/gcp-sa.json
      GCP_PROJECT_ID: ${GCP_PROJECT_ID}
      BQ_DATASET: lead_platform
      POLL_WINDOW_SECONDS: 86400
      CURSOR_FILE: /opt/airflow/project/.cursor_invoice_paid.json
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./secrets:/opt/airflow/secrets
      - ..:/opt/airflow/project
    command: bash -lc "airflow db init"
  
  grafana:
    image: grafana/grafana:11.6.3
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./secrets:/opt/grafana/secrets
      - ./provisioning:/etc/grafana/provisioning
    restart: unless-stopped

volumes:
  postgres-db-volume:
  grafana-storage: